### ISSUE TITLE
[FEATURE] Can we get all free icons available in font awesome 6?

### ISSUE THREAD

**Issue by IAmRC1** [creecros/simple_logo_gen#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by palcarazm** [comment]
Hi @IAmRC1 , 

Thanks for your issue. 

I'll check if the icons selector component has release a version with font-awesome 6 support.

**Comment by palcarazm** [comment]
The dependence hasn't released a new version, and including new icons manually breaks the "intelligence search" (keeping the search by name).

**Comment by palcarazm** [comment]
Hi @IAmRC1,

The icon-selector package has confirmed that they will not support Font Awesome 6. I will fork it and try to upgrade it ASAP.
