### ISSUE TITLE
size bug

### ISSUE THREAD

**Issue by Only1337** [creecros/simple_logo_gen#4]
https://user-images.githubusercontent.com/47225461/171998813-e8a26aa3-d35a-4bed-b500-227a417b388e.mp4

**Comment by creecros** [comment]
what are you showing me?

**Comment by Only1337** [comment]
> what are you showing me?

some fonts have clipping in letters like y and g

**Comment by creecros** [comment]
got it, hard to see black on black. probably the canvas size.

**Comment by palcarazm** [comment]
I have opened a PR #5 that fixes the issue 😄
