### ISSUE TITLE
Splitting JS in multiple files

### ISSUE THREAD

**Issue by palcarazm** [creecros/simple_logo_gen#8]
Hi @creecros , 

What do you think about splitting JS in 3 files for improving readability and keep the project easy to maintain? 

I think a refactor with:

- defaults.js: with the default parameters, ihm/libs configuration and redefining var with a speaking name. 
- listeners.js: with the declarations of all the listeners. 
- functions.js: with all app functions.

**Comment by creecros** [comment]
no issues here. welcome to do whatever you want. sorry I don't have the time or focus to help at the moment.
